#!/bin/sh

#
# 2023-08-15 for ASUS TUFF 32" 1440p monitor connected via HDMI
# HDMI only supports 60ms refresh rate 
#
# Connect to second monitor to my Razer laptop. 
# for windowmanagers that don't do this automagically
#

xrandr --output HDMI-1-0 --mode 2560x1440 -r 59.94 --right-of eDP-1
