format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$c\
$python\
$lua\
$shell\
$cmd_duration $jobs\
$line_break\
$character"""

[username]
disabled = true

[hostname]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"

[c]
format = "[$symbol($version )]($style)"
style = "bold blue"

[python]
format = "[$symbol($version )]($style)"
style = "bold green"
symbol = "python "

[lua]
format = "[$symbol($version )]($style)"
style = "purple"

[shell]
format = "[$symbol($version )]($style)"
style = "green"
disabled = false

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](bold purple)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"

[git_branch]
format = "[$symbol$branch]($style) "
style = "bright-green"
symbol = " "

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[memory_usage]
symbol = " "

[rust]
symbol = " "

[time]
disabled = false
style = "bold white"
format = "[$time]($style)"
